# baseURL = "https://example.edu"
languageCode = "en-us"
title = "Mingxin Guo"
theme = "avicenna"
googleAnalytics = "UA-1234-6"
timeout=3000
copyright = "Copyright notice © 2021"

[params]
  subtitle= "PhD Student"
  interests="Computer Architecture, Machine Learning "
  cv_name= "MingxinGuo_CV.pdf"
  blog="http://guomx.netlify.app/"

[[params.affilation]]
  name = "University of Chinese Academy of Sciences (2021- )"
  position = "PhD Student"
  # contact = "guomx.mail@gmail.com"

[[params.affilation]]
  name = "China University of Geosciences，Beijing (2017-2021)"
  position = "BSc Student"
  contact = "guomx.mail@gmail.com"


[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/mingxin-guo"

[[params.social]]
  name = "GitLab"
  icon = "gitlab"
  # url = "https://twitter.com/hadisinaee"


[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  # url = "https://linkedin.com/in/hadisinaee/"


[[params.introduction.paragraph]]
  text=""" Mingxin Guo is a currently a first-year Ph.D. student in Pattern Recognition and Intelligent System at Institute of Automation，
		Chinese Academy of Sciences.
   """
# [[params.introduction.paragraph]]
#  text=""" Pellentesque nec nam aliquam sem et tortor consequat id porta.
#	Viverra suspendisse potenti nullam ac. Leo vel orci porta non pulvinar neque laoreet.
#	Nulla facilisi nullam vehicula ipsum a arcu. Tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse.
#	Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Dui sapien eget mi proin sed libero.
#	Quam pellentesque nec nam aliquam sem et tortor consequat id. Aliquet lectus proin nibh nisl.
#  """

 [[params.publications]]
  year="Preprint"

  [[params.publications.paper]]
    name = "Wainting..."
#    authors = "__Hadi Sinaee__, ..."
#    dest  = "Helga Zita Journal"
#    link = "https://mypaperishere.com"
#    code_link = "https://thecoderepo.com"
#    blog_link = "https://myblogaboutit.com"

[[params.publications]]
  year="2020"

  [[params.publications.paper]]
		name = "GPUs-RRTMG_LW: high-efficient and scalable computing for a longwave radiative transfer model on multiple GPUs"
		authors = "Yuzhu Wang, __Mingxin Guo__, Yuan Zhao, Jinrong Jiang"
		dest  = "The Journal of Supercomputing"
		link = "https://link.springer.com/article/10.1007/s11227-020-03451-3"
		code_link = "www.github.com"
		blog_link = ""


[[params.projects]]
 [[params.projects.project]]
		name = "hugo + netlify 实现个人主页"
		# description  = "Enim facilisis gravida neque convallis a. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse.Velit egestas dui id ornare arcu odio ut sem. Nec nam aliquam sem et tortor. In nisl nisi scelerisque eu ultrices vitae auctor."
		project_page = "https://guomx1.netlify.app/"
		code_link = "https://github.com/mingxin-guo/guomx"
		# blog_link = "https://ablogpost.com"

#  [[params.projects.project]]
# 		name = "In nisl nisi scelerisque eu ultrices vitae auctor"
# 		description  = ""
#		project_page = "https://myprojecthomepage.com"
#		code_link = "https://coderepo.com"
#		blog_link = ""




[[params.experience]]
	[[params.experience.experience]]
		name = "一生一芯 （鹏城实验室, 深圳）"
		description  = "Soc设计"
		project_page = "https://myprojecthomepage.com"
		code_link = "https://www.google.com"
		#blog_link = "https://ablogpost.com"
